#!/bin/sh

set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
DEFAULT_SRC_DIR="$ROOT_DIR/agents-src"
SRC_DIR="${WORKSPACE_AGENTS_DIR:-$DEFAULT_SRC_DIR}"
CLAUDE_DIR="$ROOT_DIR/.claude/agents"
GEMINI_FILE="$ROOT_DIR/GEMINI.md"
CODEX_FILE="$ROOT_DIR/AGENTS.md"
CODEX_HARNESS_FILE="$ROOT_DIR/docs/codex-multi-agent.md"

if [ ! -d "$SRC_DIR" ]; then
  echo "Missing source directory: $SRC_DIR" >&2
  exit 1
fi

WORKSPACE_AGENTS_DIR="$SRC_DIR" sh "$ROOT_DIR/scripts/validate-agents.sh"
WORKSPACE_AGENTS_DIR="$SRC_DIR" sh "$ROOT_DIR/scripts/lint-agents.sh"

mkdir -p "$CLAUDE_DIR"

extract_field() {
  field_name=$1
  file_path=$2

  awk -F': ' -v key="$field_name" '
    BEGIN { in_header = 0 }
    $0 == "---" && in_header == 0 { in_header = 1; next }
    $0 == "---" && in_header == 1 { exit }
    in_header == 1 && $1 == key { print substr($0, length(key) + 3); exit }
  ' "$file_path"
}

strip_frontmatter() {
  file_path=$1

  awk '
    BEGIN { dash_count = 0 }
    NR == 1 && $0 == "---" { dash_count = 1; next }
    dash_count == 1 && $0 == "---" { dash_count = 2; next }
    dash_count == 0 || dash_count == 2 { print }
  ' "$file_path"
}

source_label() {
  if [ "$SRC_DIR" = "$DEFAULT_SRC_DIR" ]; then
    printf 'agents-src/*.md'
  else
    printf '%s/**/*.md' "$SRC_DIR"
  fi
}

relative_to_source() {
  file_path=$1
  printf '%s' "${file_path#$SRC_DIR/}"
}

display_path() {
  file_path=$1

  case "$file_path" in
    "$ROOT_DIR"/*)
      printf '%s' "${file_path#$ROOT_DIR/}"
      ;;
    *)
      printf '%s' "$file_path"
      ;;
  esac
}

build_registry() {
  find "$SRC_DIR" -type f -name '*.md' | sort | while IFS= read -r file_path; do
    agent_name=$(extract_field "name" "$file_path")
    agent_title=$(extract_field "title" "$file_path")
    agent_description=$(extract_field "description" "$file_path")
    rel_path=$(relative_to_source "$file_path")

    if [ -z "$agent_name" ] || [ -z "$agent_title" ] || [ -z "$agent_description" ]; then
      echo "Missing metadata in $file_path" >&2
      exit 1
    fi

    printf '%s\t%s\t%s\t%s\t%s\n' "$agent_name" "$agent_title" "$agent_description" "$rel_path" "$file_path"
  done
}

write_claude_agents() {
  build_registry | while IFS="$(printf '\t')" read -r agent_name agent_title agent_description rel_path file_path; do
    target_file="$CLAUDE_DIR/$rel_path"
    target_dir=$(dirname "$target_file")
    mkdir -p "$target_dir"

    {
      printf '# %s\n\n' "$agent_title"
      printf '> Synced from `%s/%s`. Edit the source file, then rerun `WORKSPACE_AGENTS_DIR=%s ./scripts/sync-agents.sh`.\n\n' "$SRC_DIR" "$rel_path" "$SRC_DIR"
      strip_frontmatter "$file_path"
    } > "$target_file"
  done
}

write_tree_index() {
  build_registry | while IFS="$(printf '\t')" read -r agent_name agent_title agent_description rel_path file_path; do
    printf '| `%s` | `%s` | %s | %s |\n' "$agent_name" "$rel_path" "$agent_title" "$agent_description"
  done
}

write_index_file() {
  target_file=$1
  tool_name=$2

  {
    printf '# Shared Agent Registry\n\n'
    printf 'This file is generated by `./scripts/sync-agents.sh`.\n'
    printf 'Do not edit this file directly. Update the shared source files instead.\n\n'

    printf '## Source\n\n'
    printf -- '- Source root: `%s`\n' "$SRC_DIR"
    printf -- '- Source pattern: `%s`\n' "$(source_label)"
    printf -- '- Claude output: `.claude/agents/<same-relative-path>.md`\n'
    printf -- '- %s should use the registry below to choose the right specialist prompt.\n\n' "$tool_name"

    printf '## Routing Rules\n\n'
    printf -- '- Use `planner` for task decomposition, sequencing, assumptions, and execution framing.\n'
    printf -- '- Use `reviewer` for bug finding, regression review, and test-gap inspection.\n'
    printf -- '- Use `implementer` for code changes, focused fixes, and verification work.\n'
    printf -- '- If a future specialized agent exists in a deeper folder, prefer the most specific match over a generic root agent.\n'
    printf -- '- If multiple roles apply, start with planning, then implementation, then review.\n\n'

    if [ "$tool_name" = "Codex" ]; then
      printf '## Codex Quick Start\n\n'
      printf -- '- Read `docs/codex-agent-onboarding.md` for the operating model.\n'
      printf -- '- Treat each agent file as a task-specific working standard, not as a replacement for repository rules.\n'
      printf -- '- For multi-step work, choose one planner, one implementer, and one reviewer in sequence.\n\n'

      printf '## Domain Routing\n\n'
      printf '| If the request mentions | Prefer |\n'
      printf '| --- | --- |\n'
      printf '| mobile, app, Expo, React Native, screen, navigation | `mobile/rn-implementer` or `mobile/rn-reviewer` |\n'
      printf '| admin, dashboard, moderation, queue, Next.js, web admin | `admin/nextjs-implementer` or `admin/nextjs-reviewer` |\n'
      printf '| types, schema, shared contract, mock data, fixtures | `backend-data/contracts-implementer` or `backend-data/mockdata-reviewer` |\n'
      printf '| flow, product journey, requirements, sequencing | `product/flow-planner` or root `planner` |\n'
      printf '| CI, scripts, tooling, validation, release | `ops/ci-reviewer` or `ops/release-planner` |\n'
      printf '\n'
    fi

    printf '## Agent Tree\n\n'
    printf '| id | source | title | purpose |\n'
    printf '| --- | --- | --- | --- |\n'
    write_tree_index
    printf '\n'
  } > "$target_file"
}

write_codex_harness() {
  {
    printf '# Codex Multi-Agent Harness\n\n'
    printf 'This file is generated by `./scripts/sync-agents.sh`.\n'
    printf 'It explains how shared agent definitions should be used when coordinating work in Codex.\n\n'

    printf '## Goals\n\n'
    printf -- '- Keep a single shared prompt source in `%s`.\n' "$SRC_DIR"
    printf -- '- Preserve folder structure so specialized agents can be organized by domain.\n'
    printf -- '- Route planning, implementation, and review work predictably.\n\n'

    printf '## Coordination Model\n\n'
    printf '1. Pick the narrowest agent whose source path matches the task domain.\n'
    printf '2. If no domain-specific agent exists, fall back to the root generic agents.\n'
    printf '3. For multi-phase work, apply agents in this order: planner -> implementer -> reviewer.\n'
    printf '4. Keep ownership boundaries clear when parallel work is used.\n'
    printf '5. Do not let one agent redefine repository-wide rules already stated in `AGENTS.md`.\n\n'

    printf '## Suggested Folder Convention\n\n'
    printf -- '- `workspace/agents/planner.md`: generic planning role\n'
    printf -- '- `workspace/agents/reviewer.md`: generic review role\n'
    printf -- '- `workspace/agents/implementer.md`: generic implementation role\n'
    printf -- '- `workspace/agents/mobile/*.md`: Expo and React Native specialists\n'
    printf -- '- `workspace/agents/admin/*.md`: Next.js admin specialists\n'
    printf -- '- `workspace/agents/backend-data/*.md`: shared contracts and mock-data specialists\n'
    printf -- '- `workspace/agents/backend-api/*.md`: API, service, and database specialists\n'
    printf -- '- `workspace/agents/desktop/*.md`: desktop client specialists\n'
    printf -- '- `workspace/agents/data-science/*.md`: analysis, model, and experiment specialists\n'
    printf -- '- `workspace/agents/product/*.md`: product flow planning specialists\n'
    printf -- '- `workspace/agents/ops/*.md`: CI, deployment, or infra specialists\n\n'

    printf '## Current Registry\n\n'
    printf '| id | source | title | purpose |\n'
    printf '| --- | --- | --- | --- |\n'
    write_tree_index
    printf '\n'
  } > "$CODEX_HARNESS_FILE"
}

write_codex_onboarding() {
  onboarding_file="$ROOT_DIR/docs/codex-agent-onboarding.md"

  {
    printf '# Codex Agent Onboarding\n\n'
    printf '이 문서는 이 저장소에서 Codex가 공용 에이전트를 어떻게 읽고, 어떤 순서로 쓰고, 언제 어떤 역할을 고르는지 빠르게 이해하기 위한 온보딩 문서다.\n\n'
    printf '## 시작점\n\n'
    printf 'Codex가 이 저장소에서 에이전트를 사용할 때 먼저 보는 파일은 아래 순서다.\n\n'
    printf '1. `AGENTS.md`\n'
    printf '2. `docs/codex-multi-agent.md`\n'
    printf '3. `%s/**/*.md`\n\n' "$SRC_DIR"
    printf '## 핵심 원칙\n\n'
    printf -- '- 가장 좁고 구체적인 역할을 먼저 고른다.\n'
    printf -- '- 도메인 역할이 없으면 root generic 역할로 내려간다.\n'
    printf -- '- 복합 작업은 `planner -> implementer -> reviewer` 순서로 생각한다.\n'
    printf -- '- 에이전트는 저장소 규칙을 덮어쓰는 존재가 아니라 작업 집중도를 높이는 역할 프롬프트다.\n'
    printf -- '- 좋은 에이전트는 장황한 페르소나보다 체크리스트와 경계가 명확하다.\n\n'
    printf '## 빠른 라우팅\n\n'
    printf '| 요청 유형 | 1차 역할 | 2차 역할 |\n'
    printf '| --- | --- | --- |\n'
    printf '| 요구사항 정리, 범위 나누기, 단계 계획 | `planner` 또는 `product/flow-planner` | `ops/release-planner` |\n'
    printf '| 모바일 UI/플로우 수정 | `mobile/rn-implementer` | `mobile/rn-reviewer` |\n'
    printf '| 관리자 웹 수정 | `admin/nextjs-implementer` | `admin/nextjs-reviewer` |\n'
    printf '| 타입, 계약, mock data 수정 | `backend-data/contracts-implementer` | `backend-data/mockdata-reviewer` |\n'
    printf '| 코드 리뷰, 버그 찾기 | 도메인 reviewer | root `reviewer` |\n'
    printf '| 검증 범위, 릴리즈 준비 | `ops/release-planner` | `ops/ci-reviewer` |\n'
    printf '| CI, 스크립트, 툴링 점검 | `ops/ci-reviewer` | root `reviewer` |\n\n'
    printf '## 병렬 작업 원칙\n\n'
    printf -- '- 같은 파일을 두 역할이 동시에 만지지 않게 한다.\n'
    printf -- '- 병렬화는 도메인이 분리될 때만 한다.\n'
    printf -- '- planner가 먼저 소유 범위를 나누고 implementer들이 작업한 뒤 reviewer가 통합 검토하는 흐름이 가장 안전하다.\n\n'
    printf '## 표준\n\n'
    printf -- '- 에이전트 구조와 이름 규칙은 `docs/agent-taxonomy.md`를 따른다.\n'
    printf -- '- 검증 명령: `WORKSPACE_AGENTS_DIR=%s sh ./scripts/validate-agents.sh`\n\n' "$SRC_DIR"
    printf '## 반영 명령\n\n'
    printf '```sh\n'
    printf 'npm run sync:workspace-agents\n'
    printf '```\n'
  } > "$onboarding_file"
}

write_claude_agents
write_index_file "$GEMINI_FILE" "Gemini"
write_index_file "$CODEX_FILE" "Codex"
write_codex_harness
write_codex_onboarding

printf 'Synced agents from %s\n' "$SRC_DIR"
printf 'Claude agents: %s\n' "$CLAUDE_DIR"
printf 'Gemini index: %s\n' "$GEMINI_FILE"
printf 'Codex index: %s\n' "$CODEX_FILE"
printf 'Codex harness: %s\n' "$CODEX_HARNESS_FILE"
